# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PodsPublish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodsPublish

  target 'PodsPublishTests' do
    # Pods for testing
  end

end
